version: '3.8'
services:
  mysql-master:
    image: mysql:8
    container_name: mysql-master1
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    volumes:
      - mysql-master-data:/var/lib/mysql
    ports:
      - "3310:3306"
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=test_db

  mysql-slave:
    image: mysql:8
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: slave_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    volumes:
      - mysql-slave-data:/var/lib/mysql
    ports:
      - "3311:3306"
    command:
      --server-id=2
      --log-bin=mysql-bin
      --binlog-do-db=test_db
    depends_on:
      - mysql-master

volumes:
  mysql-master-data:
  mysql-slave-data: