version: '3'

services:
  canal-server:
    image: canal/canal-server:v1.1.4
    container_name: canal-server
    restart: unless-stopped
#    network_mode: bridge
    ports:
      - 11111:11111
    environment:
      - canal.auto.scan=false
      - canal.instance.mysql.slaveId=10
      - canal.instance.master.address=172.22.0.3:3306
      - canal.instance.dbUsername=replication_user
      - canal.instance.dbPassword=123456
      - canal.instance.filter.regex=.*\\..*
      - canal.destinations=va
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=false
    volumes:
      - ./canal-server/conf/:/admin/canal-server/conf/
      - ./canal-server/logs/:/admin/canal-server/logs/
    networks:
      - test_mysql_slave

networks:
  test_mysql_slave:
    driver: bridge