version: '3.8'
services:
  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: container-canal-server
    restart: always
    volumes:
      - ./config/canal-server:/home/admin/canal-server/conf
      - ./logs/canal-server:/home/admin/canal-server/logs
    privileged: true
    environment:
      - canal.auto.scan=true
      - canal.destinations=sxxCanalInstanceName # canal实例名称，根据自己喜好命名
      - canal.instance.mysql.slaveId=1085 # canal作为模仿从站的ID，不可与主站重复
      - canal.instance.master.address=127.0.0.1:3310 #mysql的连接地址
      - canal.instance.dbUsername=replication_password # mysql的用户
      - canal.instance.dbPassword=123456 # mysql的密码
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.instance.gtidon=false
      - canal.instance.parser.parallelThreadSize=16
      - canal.instance.filter.regex=dbname.tablename # 此处为监听的正则表达式过滤，具体参考官网配置，多个用英文逗号隔开",",例如：dbname.tablename1,dbname.tablename2
  #  depends_on:
  #    - mysql
  #  links:
  #    - mysql
  #  networks:
  #    - container-net
